export default function Portfolio() {
    return(
        <div>
            <h2>Front-end</h2>
            <p>HTML5</p>
            <p>CSS</p>
            <p>JAVASCRIPT</p>
            <p>Jquery</p>
            <p>Bootstrap</p>
            <p>React</p>
            <h2>Back-end</h2>
            <p>NodeJs</p>
            <p>ExpressJs</p>
            <p>Mysql</p>
            <p>MongoDb</p>
            <p></p>
        </div>
    )
}